# Generated by Django 3.1.5 on 2021-01-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_badpostwarning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Hello', on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
