# Generated by Django 3.1.5 on 2021-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210120_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
