# Generated by Django 3.1.5 on 2021-01-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210120_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badpostwarning',
            old_name='post_slug',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_slug',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_slug',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postview',
            old_name='post_slug',
            new_name='post',
        ),
    ]
