# Generated by Django 3.1.5 on 2021-01-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_badcommentwarning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
